CREATE TABLE IF NOT EXISTS posts (id INT AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(255) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL, excerpt TEXT NOT NULL, category VARCHAR(50) NOT NULL, author_name VARCHAR(255) NOT NULL, author_role VARCHAR(255) NOT NULL, author_avatar VARCHAR(500) NOT NULL, published_date DATE NOT NULL, read_time VARCHAR(50) NOT NULL, featured TINYINT(1) NOT NULL DEFAULT 0, image VARCHAR(500) NOT NULL, content LONGTEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO posts (slug, title, excerpt, category, author_name, author_role, author_avatar, published_date, read_time, featured, image, content)
VALUES ('how-to-build-a-capsule-wardrobe-that-actually-works', 'How to Build a Capsule Wardrobe That Actually Works', 'A practical, no-nonsense approach to fewer clothes and more outfits - without another Pinterest board you''ll never open again.', 'lifestyle', 'Leo Bianchi', 'Lifestyle Editor', 'https://i.pravatar.cc/150?u=leo-bianchi-rsd', '2026-07-19', '7 min read', 0, 'https://picsum.photos/seed/how-to-build-a-capsule-wardrobe-that-actually-works/1200/800', '[{"type":"paragraph","text":"Capsule wardrobes have a branding problem. They sound restrictive, like a rulebook for people who enjoy denying themselves things. In practice, a good one is the opposite - it''s about removing friction, not adding limits."},
{"type":"paragraph","text":"Start with what you already reach for. Before buying anything, spend two weeks tracking what you actually wear. You''ll likely find it''s a smaller list than your closet suggests, and that list is your real starting palette."},
{"type":"heading","text":"Building around a neutral base"},
{"type":"paragraph","text":"Charcoal, cream, and one warm accent tone go a long way. Once the base pieces coordinate with each other by default, getting dressed stops being a decision and starts being a formality."},
{"type":"paragraph","text":"The goal isn''t fewer clothes for its own sake. It''s a closet where nearly everything works with everything else, so the only real question in the morning is what you feel like wearing."}]');
INSERT INTO posts (slug, title, excerpt, category, author_name, author_role, author_avatar, published_date, read_time, featured, image, content)
VALUES ('the-quiet-appeal-of-analog-hobbies', 'The Quiet Appeal of Analog Hobbies', 'Film cameras, paper maps, letterpress cards - why doing things the slow, imperfect way has become its own kind of luxury.', 'lifestyle', 'Jonas Willett', 'Staff Writer', 'https://i.pravatar.cc/150?u=jonas-willett-rsd', '2026-06-30', '6 min read', 0, 'https://picsum.photos/seed/the-quiet-appeal-of-analog-hobbies/1200/800', '[{"type":"paragraph","text":"I bought a film camera on a whim two years ago, mostly out of nostalgia. What kept me shooting with it had nothing to do with nostalgia at all - it was the wait. Twenty-four exposures, then a week before you see any of them."},
{"type":"paragraph","text":"That delay changes how you shoot. You think harder about the frame because you can''t check it immediately. You take fewer photos and, somehow, end up with more that actually matter."},
{"type":"heading","text":"Friction as a feature"},
{"type":"paragraph","text":"The same logic shows up in a lot of analog hobbies - hand-writing letters, using a paper map instead of a phone, cooking from a printed recipe instead of a scrolling video. The extra effort isn''t a bug. It''s what makes the activity feel like it belongs to you rather than to an algorithm."}]');
INSERT INTO posts (slug, title, excerpt, category, author_name, author_role, author_avatar, published_date, read_time, featured, image, content)
VALUES ('the-grandmothers-who-keep-a-cuisine-alive', 'The Grandmothers Who Keep a Cuisine Alive', 'In a small kitchen outside Palermo, three generations of women still make the same Sunday sauce - and the recipe has never been written down.', 'culture', 'Amara Osei', 'Culture Editor', 'https://i.pravatar.cc/150?u=amara-osei-rsd', '2026-08-01', '9 min read', 0, 'https://picsum.photos/seed/the-grandmothers-who-keep-a-cuisine-alive/1200/800', '[{"type":"paragraph","text":"Nonna Concetta doesn''t measure anything. Salt goes in by feel, the tomatoes go in when they smell right, and the sauce is done when it''s done - not a minute before, no matter what the clock says."},
{"type":"paragraph","text":"For three generations, the Sunday sauce in this kitchen has passed down through watching, not writing. Her daughter learned by standing at her elbow. Her granddaughter is learning the same way now, phone camera rolling, half for memory and half in case the details slip."},
{"type":"heading","text":"A recipe that resists translation"},
{"type":"paragraph","text":"Ask Concetta for exact quantities and she laughs. It isn''t that she''s withholding the recipe - it''s that the recipe was never really about quantities. It''s about the sound the garlic makes when it''s ready, the color of the oil, decisions made by instinct built over sixty years of Sundays."},
{"type":"quote","text":"You don''t learn this from a card. You learn it from standing here long enough that your hands remember before your head does."},
{"type":"paragraph","text":"That''s the quiet threat facing a lot of home cuisines - not that anyone stops caring, but that the knowledge only exists in kitchens like this one, passed down in person, one Sunday at a time."}]');
INSERT INTO posts (slug, title, excerpt, category, author_name, author_role, author_avatar, published_date, read_time, featured, image, content)
VALUES ('night-markets-and-the-art-of-eating-standing-up', 'Night Markets and the Art of Eating Standing Up', 'From Taipei to Oaxaca, the world''s best meals rarely come with a tablecloth - here''s what night markets teach us about food and community.', 'culture', 'Amara Osei', 'Culture Editor', 'https://i.pravatar.cc/150?u=amara-osei-rsd', '2026-07-10', '7 min read', 0, 'https://picsum.photos/seed/night-markets-and-the-art-of-eating-standing-up/1200/800', '[{"type":"paragraph","text":"There''s no reservation system at a night market, no hostess, no menu with a wine pairing suggestion. There''s a plastic stool if you''re lucky, a stranger''s elbow next to yours, and a vendor who has made the same dish ten thousand times."},
{"type":"paragraph","text":"What struck me most across markets in Taipei, Oaxaca, and Marrakech wasn''t the food itself, though it was extraordinary - it was how little ceremony surrounded it. Eating well didn''t require a special occasion. It just required showing up hungry."},
{"type":"heading","text":"Food without the formality"},
{"type":"paragraph","text":"Night markets strip dining down to its essentials: good ingredients, someone who knows exactly what to do with them, and a crowd that agrees they''ve found something worth standing in line for. There''s a lesson in there for how we think about food back home, where a good meal has come to imply a certain amount of production."}]');
