DROP TABLE IF EXISTS posts;
CREATE TABLE posts (id INT AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(255) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL, excerpt TEXT NOT NULL, category VARCHAR(50) NOT NULL, author_name VARCHAR(255) NOT NULL, author_role VARCHAR(255) NOT NULL, author_avatar VARCHAR(500) NOT NULL, published_date DATE NOT NULL, read_time VARCHAR(50) NOT NULL, featured TINYINT(1) NOT NULL DEFAULT 0, image VARCHAR(500) NOT NULL, content LONGTEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO posts (slug, title, excerpt, category, author_name, author_role, author_avatar, published_date, read_time, featured, image, content)
VALUES ('slow-mornings-in-lisbon', 'Slow Mornings in Lisbon', 'Why the best way to know a city is to wake up early, find a bakery, and let the rest of the day unfold on its own schedule.', 'travel', 'Maya Ferreira', 'Travel Editor', 'https://i.pravatar.cc/150?u=maya-ferreira-rsd', '2026-08-12', '6 min read', 1, 'https://picsum.photos/seed/slow-mornings-in-lisbon/1200/800', '[{"type":"paragraph","text":"Lisbon does not ask to be rushed. The trams still climb the same hills they did a century ago, the pastelarias open before the sun has cleared the rooftops, and nobody seems to be in a hurry to get anywhere in particular. I spent five mornings doing exactly one thing before nine a.m.: walking, without a destination, until I found somewhere serving coffee."},
{"type":"heading","text":"The ritual of the first coffee"},
{"type":"paragraph","text":"There is a particular quiet to a Lisbon cafe at seven in the morning - the espresso machine hissing, a handful of regulars reading the paper standing up at the counter, the smell of custard tart just out of the oven. I learned to order a bica and a pastel de nata and say nothing else, and it was enough to be waved toward a stool by the window."},
{"type":"paragraph","text":"By the third morning I had a route: down through Alfama''s narrow stairs while the laundry lines were still damp, along the river where the light comes in low and gold, and back up through streets that hadn''t yet filled with tourists. None of it was planned. All of it became the part of the trip I remember most clearly."},
{"type":"quote","text":"You don''t need an itinerary to know a place. You need one good bakery and the willingness to get a little lost on the way there."},
{"type":"paragraph","text":"If you''re planning your own trip, resist the urge to fill every morning with a museum or a monument. Leave the first two hours of the day empty. Let the city fill them for you."}]');
INSERT INTO posts (slug, title, excerpt, category, author_name, author_role, author_avatar, published_date, read_time, featured, image, content)
VALUES ('the-night-trains-of-eastern-europe', 'The Night Trains of Eastern Europe', 'A love letter to the sleeper cars, border checks, and unexpected conversations that come with crossing a continent after dark.', 'travel', 'Jonas Willett', 'Staff Writer', 'https://i.pravatar.cc/150?u=jonas-willett-rsd', '2026-07-28', '8 min read', 0, 'https://picsum.photos/seed/the-night-trains-of-eastern-europe/1200/800', '[{"type":"paragraph","text":"There''s a specific kind of stillness that settles over a sleeper compartment once the conductor has checked your ticket and the corridor lights dim. Outside, fields and small stations blur past in the dark. Inside, four strangers negotiate who gets the top bunk."},
{"type":"paragraph","text":"I''ve taken the overnight train between Budapest and Krakow three times now, and no two trips have looked the same. Once it was a retired geologist who spent an hour explaining the limestone formations we couldn''t see. Another time it was two students heading home for a wedding, sharing a bag of langos through the dark."},
{"type":"heading","text":"Why the slow way still wins"},
{"type":"paragraph","text":"A budget flight would get you there in under two hours. But you''d miss the border crossing at 3 a.m., the half-asleep passport checks, the way the whole car goes quiet and then, somehow, back to laughing within minutes. Night trains compress a journey into something communal in a way air travel rarely manages."},
{"type":"paragraph","text":"Bring your own snacks, a scarf that doubles as a pillow, and low expectations for sleep. What you get in return is a version of travel that feels increasingly rare - unhurried, a little uncomfortable, and genuinely memorable."}]');
INSERT INTO posts (slug, title, excerpt, category, author_name, author_role, author_avatar, published_date, read_time, featured, image, content)
VALUES ('packing-light-for-three-months', 'Packing Light for Three Months', 'Everything I learned about carry-on-only travel after a season of moving between six countries with one bag.', 'travel', 'Maya Ferreira', 'Travel Editor', 'https://i.pravatar.cc/150?u=maya-ferreira-rsd', '2026-06-15', '5 min read', 0, 'https://picsum.photos/seed/packing-light-for-three-months/1200/800', '[{"type":"paragraph","text":"The bag was 40 liters. The trip was three months, six countries, and every kind of weather from alpine cold to coastal humidity. Here''s what actually made the cut, and what I mailed home after week two."},
{"type":"paragraph","text":"The rule that saved me: everything had to work at least two ways. One rain shell that also worked as a windbreaker for early flights. One pair of shoes that could handle a hike and a nice dinner without looking like it was trying too hard at either."},
{"type":"heading","text":"What I actually wore, daily"},
{"type":"paragraph","text":"Four merino t-shirts, two pairs of trousers, one packable dress, a compression cube for the layers I hoped not to need. Laundry became a weekly ritual rather than an emergency, usually done in a sink with travel detergent and a lot of patience."},
{"type":"paragraph","text":"The biggest lesson wasn''t about gear at all - it was that owning less on the road made decisions faster. Fewer choices in the morning meant more time for the parts of the trip that actually mattered."}]');
INSERT INTO posts (slug, title, excerpt, category, author_name, author_role, author_avatar, published_date, read_time, featured, image, content)
VALUES ('the-case-for-a-slower-morning-routine', 'The Case for a Slower Morning Routine', 'No cold plunges, no five a.m. alarms - just a handful of small habits that make the first hour of the day feel like yours again.', 'lifestyle', 'Leo Bianchi', 'Lifestyle Editor', 'https://i.pravatar.cc/150?u=leo-bianchi-rsd', '2026-08-05', '5 min read', 0, 'https://picsum.photos/seed/the-case-for-a-slower-morning-routine/1200/800', '[{"type":"paragraph","text":"Somewhere along the way, the morning routine became a competitive sport - cold plunges, sunrise runs, journaling prompts, a supplement stack that needs its own shelf. I tried most of it. None of it stuck."},
{"type":"paragraph","text":"What did stick was smaller and far less photogenic: waking up without immediately reaching for my phone, making coffee slowly instead of hitting a button and walking away, and sitting somewhere with natural light for ten minutes before opening a laptop."},
{"type":"heading","text":"Small habits, compounded"},
{"type":"paragraph","text":"None of these changes were dramatic on their own. Together, they shifted how the whole day felt - less reactive, more like something I was choosing rather than something happening to me."},
{"type":"quote","text":"A morning routine doesn''t need to optimize you. It just needs to belong to you."}]');
