CREATE TABLE IF NOT EXISTS posts (id INT AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(255) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL, excerpt TEXT NOT NULL, category VARCHAR(50) NOT NULL, author_name VARCHAR(255) NOT NULL, author_role VARCHAR(255) NOT NULL, author_avatar VARCHAR(500) NOT NULL, published_date DATE NOT NULL, read_time VARCHAR(50) NOT NULL, featured TINYINT(1) NOT NULL DEFAULT 0, image VARCHAR(500) NOT NULL, content LONGTEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO posts (slug, title, excerpt, category, author_name, author_role, author_avatar, published_date, read_time, featured, image, content)
VALUES ('the-last-letterpress-in-town', 'The Last Letterpress in Town', 'A print shop that has survived three recessions and a pandemic on the strength of wedding invitations and stubborn craftsmanship.', 'culture', 'Jonas Willett', 'Staff Writer', 'https://i.pravatar.cc/150?u=jonas-willett-rsd', '2026-05-22', '6 min read', 0, 'https://picsum.photos/seed/the-last-letterpress-in-town/1200/800', '[{"type":"paragraph","text":"The presses are older than anyone currently working them. Cast iron, foot-pedaled, the kind of machine that requires you to listen to it as much as operate it. Mateo has run this shop for eleven years and can tell when a roller needs adjusting by the sound of a single pass."},
{"type":"paragraph","text":"Letterpress printing should have died decades ago, economically speaking. It''s slower and more expensive than digital printing in every measurable way. And yet the orders keep coming - wedding invitations, mostly, from people who want to feel the impression of the type pressed into heavy paper."},
{"type":"heading","text":"Slowness as the selling point"},
{"type":"paragraph","text":"''People aren''t paying for the ink,'' Mateo told me. ''They''re paying for the fact that a person had to set every letter by hand.'' In an age of instant everything, that fact alone has become the whole product."}]');
INSERT INTO posts (slug, title, excerpt, category, author_name, author_role, author_avatar, published_date, read_time, featured, image, content)
VALUES ('what-a-decade-of-journaling-taught-me', 'What a Decade of Journaling Taught Me', 'Ten years, dozens of notebooks, and one honest takeaway: the habit matters far more than the method.', 'wellness', 'Priya Nair', 'Wellness Contributor', 'https://i.pravatar.cc/150?u=priya-nair-rsd', '2026-08-18', '6 min read', 0, 'https://picsum.photos/seed/what-a-decade-of-journaling-taught-me/1200/800', '[{"type":"paragraph","text":"I''ve tried bullet journaling, gratitude lists, morning pages, and a stretch of therapy-recommended prompts I mostly ignored. What survived a decade wasn''t any particular method. It was showing up with a pen most days, even for two sentences."},
{"type":"paragraph","text":"The notebooks themselves are a strange kind of time capsule. Flipping back through them isn''t always flattering - a lot of repeated worries, the same arguments with myself. But that repetition turned out to be useful information, a pattern I couldn''t see in the moment but could see clearly on the page."},
{"type":"heading","text":"Consistency beats the perfect prompt"},
{"type":"paragraph","text":"If you''ve stalled out on journaling because you can''t find the right format, that''s the wrong problem to solve. Write badly, write short, write about nothing in particular. The format matters far less than showing up again tomorrow."}]');
INSERT INTO posts (slug, title, excerpt, category, author_name, author_role, author_avatar, published_date, read_time, featured, image, content)
VALUES ('walking-as-medicine', 'Walking as Medicine', 'No app, no plan, no destination - just forty minutes a day and a habit that quietly reshaped how I handle stress.', 'wellness', 'Priya Nair', 'Wellness Contributor', 'https://i.pravatar.cc/150?u=priya-nair-rsd', '2026-07-03', '5 min read', 0, 'https://picsum.photos/seed/walking-as-medicine/1200/800', '[{"type":"paragraph","text":"It started as a way to avoid a difficult phone call. I put on shoes, left my phone at home, and walked for forty minutes with no destination. I''ve done some version of that walk almost every day since."},
{"type":"paragraph","text":"There''s a specific kind of thinking that only seems to happen in motion - not the productive, list-making kind, but something slower and more honest. Problems that felt unsolvable at a desk tend to loosen their grip somewhere around minute twenty."},
{"type":"quote","text":"The walk rarely solves anything directly. It just makes the problem small enough to fit back in my hands."},
{"type":"paragraph","text":"No tracking, no pace goals, no app open in your pocket. The whole point is the absence of a metric - just legs, air, and enough time for your mind to catch up with itself."}]');
INSERT INTO posts (slug, title, excerpt, category, author_name, author_role, author_avatar, published_date, read_time, featured, image, content)
VALUES ('learning-to-rest-without-guilt', 'Learning to Rest Without Guilt', 'Rest isn''t a reward you earn after finishing the list. Unlearning that idea took longer than expected, and it''s still a work in progress.', 'wellness', 'Priya Nair', 'Wellness Contributor', 'https://i.pravatar.cc/150?u=priya-nair-rsd', '2026-05-29', '7 min read', 0, 'https://picsum.photos/seed/learning-to-rest-without-guilt/1200/800', '[{"type":"paragraph","text":"For most of my twenties, rest was something I had to earn. A finished to-do list came first; the nap, the slow afternoon, the guilt-free hour on the couch came after, if there was time left over. There rarely was."},
{"type":"paragraph","text":"The shift didn''t come from a single realization. It came slowly, mostly from noticing how much better my actual work got when I stopped treating rest as the thing I had to justify."},
{"type":"heading","text":"Rest as maintenance, not reward"},
{"type":"paragraph","text":"Reframing rest as maintenance rather than a prize changed the guilt equation entirely. You don''t feel guilty for changing the oil in a car you rely on. The same logic, it turns out, applies to a person."},
{"type":"paragraph","text":"It''s still a work in progress some weeks more than others. But the goal isn''t to get it perfect. It''s to keep noticing when the old rule - earn it first - starts creeping back in, and to gently set it back down."}]');
