DROP TABLE IF EXISTS posts;
CREATE TABLE posts (id INT AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(255) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL, excerpt TEXT NOT NULL, category VARCHAR(50) NOT NULL, author_name VARCHAR(255) NOT NULL, author_role VARCHAR(255) NOT NULL, author_avatar VARCHAR(500) NOT NULL, published_date DATE NOT NULL, read_time VARCHAR(50) NOT NULL, featured TINYINT(1) NOT NULL DEFAULT 0, image VARCHAR(500) NOT NULL, content LONGTEXT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO posts (slug, title, excerpt, category, author_name, author_role, author_avatar, published_date, read_time, featured, image, content)
VALUES ('slow-mornings-in-lisbon', 'Slow Mornings in Lisbon', 'Why the best way to know a city is to wake up early, find a bakery, and let the rest of the day unfold on its own schedule.', 'travel', 'Maya Ferreira', 'Travel Editor', 'https://i.pravatar.cc/150?u=maya-ferreira-rsd', '2026-08-12', '6 min read', 1, 'https://picsum.photos/seed/slow-mornings-in-lisbon/1200/800', '[{"type":"paragraph","text":"Lisbon does not ask to be rushed. The trams still climb the same hills they did a century ago, the pastelarias open before the sun has cleared the rooftops, and nobody seems to be in a hurry to get anywhere in particular. I spent five mornings doing exactly one thing before nine a.m.: walking, without a destination, until I found somewhere serving coffee."},
{"type":"heading","text":"The ritual of the first coffee"},
{"type":"paragraph","text":"There is a particular quiet to a Lisbon cafe at seven in the morning - the espresso machine hissing, a handful of regulars reading the paper standing up at the counter, the smell of custard tart just out of the oven. I learned to order a bica and a pastel de nata and say nothing else, and it was enough to be waved toward a stool by the window."},
{"type":"paragraph","text":"By the third morning I had a route: down through Alfama''s narrow stairs while the laundry lines were still damp, along the river where the light comes in low and gold, and back up through streets that hadn''t yet filled with tourists. None of it was planned. All of it became the part of the trip I remember most clearly."},
{"type":"quote","text":"You don''t need an itinerary to know a place. You need one good bakery and the willingness to get a little lost on the way there."},
{"type":"paragraph","text":"If you''re planning your own trip, resist the urge to fill every morning with a museum or a monument. Leave the first two hours of the day empty. Let the city fill them for you."}]');
